# Use 15672/user/password as port/user/password credentials

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: on-failure
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
