# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgresqldata:/var/lib/postgresql/data:rw
    network_mode: 'host'

volumes:
  postgresqldata: {}
