# Use postgres/postgres/12345 database/user/password credentials
version: '3.1'

services:
  postgresql:
    image: postgres:15
    container_name: postgres
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data:rw
    depends_on:
      - pgbouncer
  pgbouncer:
    image: bitnami/pgbouncer:1
    container_name: pgbouncer
    restart: on-failure
    ports:
      - '6432:6432'
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: 12345
      POSTGRESQL_DATABASE: postgres

volumes:
  postgresql_data:
    driver: local
