# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodbdata:/data/db:rw
    network_mode: 'host'

volumes:
  mongodbdata: {}
