# Use db/root/12345 as database/user/password credentials

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: on-failure
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_SSL: 0
    depends_on:
      - mysql

volumes:
  mysql_data:
