services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: on-failure
    ports:
      - '3000:3000'
    volumes:
      - './grafana/provisioning/:/etc/grafana/provisioning/'
      - 'grafana-data:/var/lib/grafana'
      - 'grafana-configs:/etc/grafana'
    depends_on:
      - loki
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: on-failure
    ports:
      - '3100:3100'
    command: '-config.file=/etc/loki/local-config.yaml'
    volumes:
      - 'loki-data:/loki' 
    depends_on:
      - alloy
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: on-failure
    ports:
      - '12345:12345'
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - alloy-data:/var/lib/alloy/data
    command:
      - 'run'
      - '/etc/alloy/config.alloy'
      - '--server.http.listen-addr=0.0.0.0:12345'
      - '--storage.path=/var/lib/alloy/data'

volumes:
  grafana-data:
  grafana-configs:
  loki-data:
  alloy-data:
