services:
  clickhouse:
    image: clickhouse:latest
    container_name: clickhouse
    ulimits:
      nofile: 262144
    restart: on-failure
    ports:
      - '8123:8123'
      - '9000:9000'
    environment:
      CLICKHOUSE_PASSWORD: changeme
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server

volumes:
  clickhouse_data:
  clickhouse_logs:
