version: '3.8'

services:
  clickhouse_server:
    image: yandex/clickhouse-server
    container_name: clickhouse_server
    restart: on-failure
    ports:
      - '8123:8123'
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data:
    driver: local
