version: '3.8'

services:
  garnet:
    image: ghcr.io/microsoft/garnet
    container_name: garnet
    restart: unless-stopped
    ulimits:
      memlock: -1
    ports:
      - '6379:6379'
    volumes:
      - garnet_data:/data
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - '5540:5540'
    depends_on:
      - garnet

volumes:
  garnet_data:
