# Credentials: username - postgres, password - 12345, database - postgres
# PgAdmin: host - postgres, port - 5432

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: on-failure
    ports:
      - '54321:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: on-failure
    ports:
      - '5050:5050'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 12345
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5050
    depends_on:
      - postgres

volumes:
  postgresql-data:
