# Use postgres/postgres/12345 database/user/password credentials
version: '3.8'

services:
  pgbouncer:
    image: bitnami/pgbouncer:1
    container_name: pgbouncer
    restart: on-failure
    ports:
      - '6432:6432'
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: 12345
      POSTGRESQL_DATABASE: postgres
      PGBOUNCER_IGNORE_STARTUP_PARAMETERS: extra_float_digits
  postgresql:
    image: postgres:15
    container_name: postgres
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data:rw
    depends_on:
      - pgbouncer
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: on-failure
    ports:
      - '8081:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    depends_on:
      - postgresql

volumes:
  postgresql_data:
    driver: local
