# Use db/root/12345 as database/user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: on-failure
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db
    volumes:
      - mysql_data:/var/lib/mysql:rw
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: on-failure
    ports:
      - '127.0.0.1:8081:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local
