# Use db/root/12345 as database/user/password credentials
version: '3.8'

services:
    laravel8_server:
        container_name: laravel8_server
        build: .
        restart: on-failure
        volumes:
            - ./app/:/app/app/
            - ./bootstrap/:/app/bootstrap/
            - ./config/:/app/config/
            - ./database/:/app/database/
            - ./public/:/app/public/
            - ./resources/:/app/resources/
            - ./routes/:/app/routes/
            - ./storage/:/app/storage/
            - ./tests/:/app/tests/
            - ./.env:/app/.env
            - ./artisan:/app/artisan
            - ./phpunit.xml:/app/phpunit.xml
            - ./webpack.mix.js:/app/webpack.mix.js
        ports:
            - '8000:8000'
        networks:
            - laravel8-network
        depends_on:
            - mysql
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: on-failure
        ports:
            - '3306:3306'
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: db
        volumes:
            - mysql_data:/var/lib/mysql:rw
        networks:
            - laravel8-network
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        restart: on-failure
        ports:
            - '8001:80'
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        networks:
            - laravel8-network
        depends_on:
            - mysql

networks:
    laravel8-network:
        driver: bridge

volumes:
    mysql_data:
        driver: local
