# Grafana: admin/admin

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: on-failure
    ports:
      - '3000:3000'
    volumes:
      - './grafana/provisioning/:/etc/grafana/provisioning/'
      - 'grafana-data:/var/lib/grafana'
      - 'grafana-configs:/etc/grafana'
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: on-failure
    ports:
      - '9090:9090'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
      - 'prom-data:/prometheus'
      - 'prom-configs:/etc/prometheus'
    command:
      - '--web.enable-otlp-receiver'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - node-exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: on-failure
    ports:
      - '9100:9100'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host/root'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

volumes:
  grafana-data:
  grafana-configs:
  prom-data:
  prom-configs:
